# This is a configuration file for the Github Pages edition of a book by Chastity.
# This site is managed by Chastity White Rose, the Vegan Virgin.

title: Chastity’s Chess Chapters
description: Chess is not as hard to learn as you have been told!
email: chastitywhiterose@gmail.com
footer: This site is an online copy of a book project!

